spring:
  application:
    name: shopease-backend
  
  datasource:
    url: jdbc:mysql://localhost:3306/shopease_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  
server:
  port: 8080

# JWT Configuration
jwt:
  secret: "your-very-strong-secret-key-that-is-at-least-32-characters-long"
  expiration: 86400000  # Token validity in milliseconds (24 hours)

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
